version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - express-app

  express-app:
    build: .
    # ports:
    #   - "3000:4000"
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ashjag
      MONGO_INITDB_ROOT_PASSWORD: Pass_123
    volumes:
      - mongo-db:/data/db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s
  
  redis:
    image: redis:latest
      
volumes:
  mongo-db: