version: "3"
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_USER: Ashjag
      MONGO_PASSWORD: Pass_123
    command: npm run dev
    depends_on:
      - mongo
    
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ashjag
      MONGO_INITDB_ROOT_PASSWORD: Pass_123