version: "3"
services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ashjag
      MONGO_INITDB_ROOT_PASSWORD: Pass_123
    volumes:
      - mongo-db:/data/db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s
      
volumes:
  mongo-db: