version: "3"
services:
  express-app:
    build: .
    ports:
      - "3000:4000"
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Ashjag
      - MONGO_INITDB_ROOT_PASSWORD=Pass@123
    volumes:
      - mongo-db:/data/db
      
volumes:
  mongo-db: